// 兼容代码-----------
import 'ant-design-vue/lib/anchor/style';
import 'ant-design-vue/lib/avatar/style';
import 'ant-design-vue/lib/breadcrumb/style';
import 'ant-design-vue/lib/divider/style';
import 'ant-design-vue/lib/drawer/style';
import 'ant-design-vue/lib/layout/style';
import 'ant-design-vue/lib/list/style';
import 'ant-design-vue/lib/menu/style';
import 'ant-design-vue/lib/message/style';
import 'ant-design-vue/lib/popover/style';
import 'ant-design-vue/lib/select/style';
import 'ant-design-vue/lib/space/style';
import 'ant-design-vue/lib/spin/style';
import 'ant-design-vue/lib/switch/style';
import 'ant-design-vue/lib/tabs/style';
import 'ant-design-vue/lib/tooltip/style';
import 'ant-design-vue/lib/typography/style';
//----------------------